version: '3'
services:
  app:
    container_name: meetdata-api
    restart: always
    build: .
    ports:
    - '8000:8000'
    external_links:
    - mongo

  mongo:
    container_name: mongo-server
    image: mongo:latest
    volumes:
    - ./data:/data/db
    ports:
    - '27012:27017'

  mongo-express: 
    container_name: mongo-express
    image: mongo-express
    ports: 
    - '8083:8081'